# Generated by Django 4.0.4 on 2022-06-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0012_alter_pokemon_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='foto',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
