# Generated by Django 4.0.4 on 2022-06-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0014_alter_pokemon_tipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
